// M2TW Script Autocomplete Data — extracted from Ultimate Docudemons 4.2
// Each entry: { label, type, params, desc }

export const AUTOCOMPLETE_ITEMS = [
  // ── EVENTS ──────────────────────────────────────────────────────────────────
  { label: 'PreBattle',                   type: 'event',     params: '',                                         desc: 'When a battle is about to start' },
  { label: 'PostBattle',                  type: 'event',     params: '',                                         desc: 'After a battle ends' },
  { label: 'FactionTurnStart',            type: 'event',     params: '',                                         desc: 'At the start of a faction\'s turn' },
  { label: 'FactionTurnEnd',              type: 'event',     params: '',                                         desc: 'At the end of a faction\'s turn' },
  { label: 'CharacterTurnStart',          type: 'event',     params: '',                                         desc: 'At the start of a character\'s turn' },
  { label: 'CharacterTurnEnd',            type: 'event',     params: '',                                         desc: 'At the end of a character\'s turn' },
  { label: 'GeneralCaptureSettlement',    type: 'event',     params: '',                                         desc: 'When a general captures a settlement' },
  { label: 'GeneralAssaultSettlement',    type: 'event',     params: '',                                         desc: 'When a general assaults a settlement' },
  { label: 'SettlementTurnStart',         type: 'event',     params: '',                                         desc: 'At the start of a settlement\'s turn' },
  { label: 'BattleStarted',               type: 'event',     params: '',                                         desc: 'When a battle starts' },
  { label: 'BattleEnded',                 type: 'event',     params: '',                                         desc: 'When a battle ends' },
  { label: 'FactionDestroyed',            type: 'event',     params: '',                                         desc: 'When a faction is destroyed' },
  { label: 'CharacterComesOfAge',         type: 'event',     params: '',                                         desc: 'When a character comes of age' },
  { label: 'CharacterDies',               type: 'event',     params: '',                                         desc: 'When a character dies' },
  { label: 'NewCharacter',                type: 'event',     params: '',                                         desc: 'When a new character is created' },
  { label: 'FactionLeaderDied',           type: 'event',     params: '',                                         desc: 'When the faction leader dies' },
  { label: 'AmbassadorAudience',          type: 'event',     params: '',                                         desc: 'When an ambassador has an audience' },
  { label: 'DiplomacySucceeded',          type: 'event',     params: '',                                         desc: 'When a diplomacy action succeeds' },
  { label: 'DiplomacyFailed',             type: 'event',     params: '',                                         desc: 'When a diplomacy action fails' },
  { label: 'RebelsSpawned',               type: 'event',     params: '',                                         desc: 'When rebels spawn' },
  { label: 'BuildingCompleted',           type: 'event',     params: '',                                         desc: 'When a building is completed' },
  { label: 'UnitBuilt',                   type: 'event',     params: '',                                         desc: 'When a unit is trained' },
  { label: 'UnitDisbanded',               type: 'event',     params: '',                                         desc: 'When a unit is disbanded' },
  { label: 'TradeRouteSucceeded',         type: 'event',     params: '',                                         desc: 'When a trade route succeeds' },
  { label: 'TradeRouteFailed',            type: 'event',     params: '',                                         desc: 'When a trade route fails' },
  { label: 'EndOfTurn',                   type: 'event',     params: '',                                         desc: 'At the end of the turn' },
  { label: 'StartOfTurn',                 type: 'event',     params: '',                                         desc: 'At the start of the turn' },
  { label: 'AgentCreated',                type: 'event',     params: '',                                         desc: 'When an agent is created' },
  { label: 'AgentDies',                   type: 'event',     params: '',                                         desc: 'When an agent dies' },

  // ── CONDITIONS ──────────────────────────────────────────────────────────────
  { label: 'FactionIsLocal',              type: 'condition', params: '',                                         desc: 'True if the faction is player-controlled' },
  { label: 'FactionIsHuman',              type: 'condition', params: '',                                         desc: 'True if the faction is human-controlled' },
  { label: 'FactionIsAlive',              type: 'condition', params: '',                                         desc: 'True if the faction is still alive' },
  { label: 'FactionIsDefeated',           type: 'condition', params: '',                                         desc: 'True if the faction is defeated' },
  { label: 'FactionType',                 type: 'condition', params: '<faction_type>',                           desc: 'Checks the faction type' },
  { label: 'I_InBattle',                  type: 'condition', params: '',                                         desc: 'True if currently in a battle' },
  { label: 'I_TurnNumber',                type: 'condition', params: '<operator> <value>',                       desc: 'Checks the current turn number' },
  { label: 'I_NumberOfSettlements',       type: 'condition', params: '<operator> <value>',                       desc: 'Checks the number of settlements owned' },
  { label: 'I_NumberOfUnits',             type: 'condition', params: '<faction> <operator> <value>',             desc: 'Checks the number of units' },
  { label: 'I_IsAlly',                    type: 'condition', params: '<faction>',                                desc: 'True if the faction is an ally' },
  { label: 'I_IsEnemy',                   type: 'condition', params: '<faction>',                                desc: 'True if the faction is an enemy' },
  { label: 'I_IsSameTeam',               type: 'condition', params: '<faction>',                                desc: 'True if on the same team' },
  { label: 'I_CounterEqualTo',            type: 'condition', params: '<counter_name> <value>',                   desc: 'True if the counter equals the value' },
  { label: 'I_CounterLessThan',           type: 'condition', params: '<counter_name> <value>',                   desc: 'True if the counter is less than value' },
  { label: 'I_CounterGreaterThan',        type: 'condition', params: '<counter_name> <value>',                   desc: 'True if the counter is greater than value' },
  { label: 'SettlementName',              type: 'condition', params: '<settlement_name>',                        desc: 'Checks the settlement name' },
  { label: 'TargetSettlementName',        type: 'condition', params: '<settlement_name>',                        desc: 'Checks the target settlement name' },
  { label: 'RegionName',                  type: 'condition', params: '<region_name>',                            desc: 'Checks the region name' },
  { label: 'CharacterName',              type: 'condition', params: '<character_name>',                         desc: 'Checks the character name' },
  { label: 'CharacterType',              type: 'condition', params: '<character_type>',                         desc: 'Checks the character type' },
  { label: 'IsGeneral',                   type: 'condition', params: '',                                         desc: 'True if the character is a general' },
  { label: 'IsSpy',                       type: 'condition', params: '',                                         desc: 'True if the character is a spy' },
  { label: 'IsAssassin',                  type: 'condition', params: '',                                         desc: 'True if the character is an assassin' },
  { label: 'IsAdmiral',                   type: 'condition', params: '',                                         desc: 'True if the character is an admiral' },
  { label: 'CharacterInRegion',           type: 'condition', params: '<region_name>',                            desc: 'True if the character is in the specified region' },
  { label: 'FactionInRegion',             type: 'condition', params: '<faction> <region_name>',                  desc: 'True if the faction controls the region' },
  { label: 'SettlementLevel',             type: 'condition', params: '<operator> <level>',                       desc: 'Checks the settlement level' },
  { label: 'SettlementMinLevel',          type: 'condition', params: '<level>',                                  desc: 'Checks minimum settlement level' },
  { label: 'SettlementMaxLevel',          type: 'condition', params: '<level>',                                  desc: 'Checks maximum settlement level' },
  { label: 'MoneyBalance',                type: 'condition', params: '<operator> <amount>',                      desc: 'Checks the money balance' },
  { label: 'PopulationSize',              type: 'condition', params: '<operator> <value>',                       desc: 'Checks the population size' },
  { label: 'ResourceType',                type: 'condition', params: '<resource_name>',                          desc: 'Checks for a resource type' },
  { label: 'CounterValue',                type: 'condition', params: '<counter_name> <operator> <value>',        desc: 'Checks a counter value' },
  { label: 'WonBattle',                   type: 'condition', params: '',                                         desc: 'True if the battle was won' },
  { label: 'LostBattle',                  type: 'condition', params: '',                                         desc: 'True if the battle was lost' },
  { label: 'WasAttacker',                 type: 'condition', params: '',                                         desc: 'True if the character was the attacker' },
  { label: 'WasDefender',                 type: 'condition', params: '',                                         desc: 'True if the character was the defender' },
  { label: 'IsOnCrusade',                 type: 'condition', params: '',                                         desc: 'True if the character is on crusade' },
  { label: 'IsOnJihad',                   type: 'condition', params: '',                                         desc: 'True if the character is on jihad' },
  { label: 'TurnNumber',                  type: 'condition', params: '<operator> <value>',                       desc: 'Checks the current turn number' },
  { label: 'IsNakedFanatic',              type: 'condition', params: '',                                         desc: 'True if the character is a naked fanatic' },
  { label: 'IsGunpowderUnit',             type: 'condition', params: '',                                         desc: 'True if the unit uses gunpowder' },
  { label: 'HasAncillary',               type: 'condition', params: '<ancillary_name>',                         desc: 'True if the character has the ancillary' },
  { label: 'HasTrait',                    type: 'condition', params: '<trait_name>',                             desc: 'True if the character has the trait' },
  { label: 'TraitLevel',                  type: 'condition', params: '<trait_name> <operator> <level>',          desc: 'Checks the trait level' },

  // ── COMMANDS ────────────────────────────────────────────────────────────────
  { label: 'console_command',             type: 'command',   params: '<command>',                                desc: 'Executes a console command' },
  { label: 'add_money',                   type: 'command',   params: '<faction> <amount>',                       desc: 'Adds money to a faction. e.g. add_money england, 5000' },
  { label: 'add_population',              type: 'command',   params: '<settlement> <amount>',                    desc: 'Adds population to a settlement' },
  { label: 'spawn_army',                  type: 'command',   params: '<faction> <x> <y>',                        desc: 'Spawns an army for a faction at coordinates' },
  { label: 'create_unit',                 type: 'command',   params: '<settlement> <unit_type> <quantity> <exp> <armour> <weapon>',  desc: 'Creates a unit at a settlement' },
  { label: 'create_building',             type: 'command',   params: '<settlement> <building_type>',             desc: 'Creates a building at a settlement' },
  { label: 'destroy_building',            type: 'command',   params: '<settlement> <building_type>',             desc: 'Destroys a building at a settlement' },
  { label: 'set_building_health',         type: 'command',   params: '<settlement> <building_type> <health>',    desc: 'Sets the health of a building' },
  { label: 'move_character',              type: 'command',   params: '<character_name> <x> <y>',                 desc: 'Moves a character to map coordinates' },
  { label: 'kill_character',              type: 'command',   params: '<character_name>',                         desc: 'Kills a character' },
  { label: 'give_ancillary',              type: 'command',   params: '<character_name> <ancillary_name>',        desc: 'Gives an ancillary to a character' },
  { label: 'remove_ancillary',            type: 'command',   params: '<character_name> <ancillary_name>',        desc: 'Removes an ancillary from a character' },
  { label: 'give_trait',                  type: 'command',   params: '<character_name> <trait_name> <level>',    desc: 'Gives a trait to a character' },
  { label: 'remove_trait',               type: 'command',   params: '<character_name> <trait_name>',            desc: 'Removes a trait from a character' },
  { label: 'win_campaign',                type: 'command',   params: '<faction>',                                desc: 'Forces a faction to win the campaign' },
  { label: 'lose_campaign',               type: 'command',   params: '<faction>',                                desc: 'Forces a faction to lose the campaign' },
  { label: 'show_message',                type: 'command',   params: '<message_id>',                             desc: 'Displays a message to the player' },
  { label: 'play_sound',                  type: 'command',   params: '<sound_id>',                               desc: 'Plays a sound effect' },
  { label: 'play_movie',                  type: 'command',   params: '<movie_file>',                             desc: 'Plays a video file' },
  { label: 'trigger_advice',              type: 'command',   params: '<advice_thread>',                          desc: 'Triggers an advice thread' },
  { label: 'spawn_agent',                 type: 'command',   params: '<faction> <agent_type> <name> <x> <y>',   desc: 'Spawns an agent on the map' },
  { label: 'destroy_army',               type: 'command',   params: '<faction> <x> <y>',                        desc: 'Destroys an army at a location' },
  { label: 'make_faction_ai',             type: 'command',   params: '<faction>',                                desc: 'Makes a faction AI-controlled' },
  { label: 'make_faction_player',         type: 'command',   params: '<faction>',                                desc: 'Makes a faction player-controlled' },
  { label: 'set_faction_standing',        type: 'command',   params: '<faction1> <faction2> <value>',            desc: 'Sets diplomatic standing between factions' },
  { label: 'set_region_religion',         type: 'command',   params: '<region> <religion> <value>',              desc: 'Sets the religion level in a region' },
  { label: 'historic_event',              type: 'command',   params: '<event_id>',                               desc: 'Triggers a historic event popup' },
  { label: 'show_me_message',             type: 'command',   params: '<message_id> <faction>',                   desc: 'Shows a message to a specific faction' },
  { label: 'disable_movement',            type: 'command',   params: '<faction>',                                desc: 'Disables movement for a faction' },
  { label: 'enable_movement',             type: 'command',   params: '<faction>',                                desc: 'Enables movement for a faction' },
  { label: 'clear_objectives',            type: 'command',   params: '',                                         desc: 'Clears all objectives' },
  { label: 'set_objective',               type: 'command',   params: '<objective_id> <state>',                   desc: 'Sets an objective state' },
  { label: 'destroy_unit',               type: 'command',   params: '<unit_id>',                                desc: 'Destroys a specific unit' },
  { label: 'disband_unit',               type: 'command',   params: '<unit_id>',                                desc: 'Disbands a specific unit' },
  { label: 'make_alliance',              type: 'command',   params: '<faction1> <faction2>',                    desc: 'Creates an alliance between two factions' },
  { label: 'break_alliance',             type: 'command',   params: '<faction1> <faction2>',                    desc: 'Breaks an alliance between two factions' },
  { label: 'offer_peace',                type: 'command',   params: '<faction1> <faction2>',                    desc: 'Offers peace between two factions' },
  { label: 'declare_war',                type: 'command',   params: '<faction1> <faction2>',                    desc: 'Declares war between two factions' },
  { label: 'add_unit_to_army',           type: 'command',   params: '<army_id> <unit_type>',                    desc: 'Adds a unit to an existing army' },
  { label: 'transfer_unit',              type: 'command',   params: '<unit_id> <target_army_id>',               desc: 'Transfers a unit to another army' },
  { label: 'set_scroll_speed',           type: 'command',   params: '<speed>',                                  desc: 'Sets the map scroll speed' },
  { label: 'ai_gta_plan_set',            type: 'command',   params: '<alliance_id> <plan>',                     desc: 'Sets GTA battle plan' },
  { label: 'set_counter_value',          type: 'command',   params: '<counter_name> <value>',                   desc: 'Sets a counter to a specific value' },

  // ── KEYWORDS ────────────────────────────────────────────────────────────────
  { label: 'monitor_event',              type: 'keyword',   params: '<EventName> <Condition>',                  desc: 'Opens an event monitor block' },
  { label: 'monitor_conditions',         type: 'keyword',   params: '',                                         desc: 'Opens a conditions monitor block' },
  { label: 'end_monitor',                type: 'keyword',   params: '',                                         desc: 'Closes a monitor block' },
  { label: 'if',                         type: 'keyword',   params: '<condition>',                              desc: 'Opens an if block' },
  { label: 'else',                       type: 'keyword',   params: '',                                         desc: 'Else branch of an if block' },
  { label: 'end_if',                     type: 'keyword',   params: '',                                         desc: 'Closes an if block' },
  { label: 'while',                      type: 'keyword',   params: '<condition>',                              desc: 'Opens a while loop block' },
  { label: 'end_while',                  type: 'keyword',   params: '',                                         desc: 'Closes a while loop block' },
  { label: 'declare_counter',            type: 'keyword',   params: '<counter_name> <initial_value>',           desc: 'Declares a new counter variable' },
  { label: 'set_counter',                type: 'keyword',   params: '<counter_name> <value>',                   desc: 'Sets a counter to a value' },
  { label: 'change_counter',             type: 'keyword',   params: '<counter_name> <delta>',                   desc: 'Changes a counter by a delta value' },
  { label: 'inc_counter',                type: 'keyword',   params: '<counter_name>',                           desc: 'Increments a counter by 1' },
  { label: 'dec_counter',                type: 'keyword',   params: '<counter_name>',                           desc: 'Decrements a counter by 1' },
  { label: 'clear_counter',              type: 'keyword',   params: '<counter_name>',                           desc: 'Clears (resets) a counter' },
  { label: 'store_counter',              type: 'keyword',   params: '<counter_name>',                           desc: 'Stores a counter value' },
  { label: 'restore_counter',            type: 'keyword',   params: '<counter_name>',                           desc: 'Restores a stored counter value' },
  { label: 'and',                        type: 'keyword',   params: '',                                         desc: 'Logical AND operator for conditions' },
  { label: 'or',                         type: 'keyword',   params: '',                                         desc: 'Logical OR operator for conditions' },
  { label: 'not',                        type: 'keyword',   params: '',                                         desc: 'Logical NOT operator for conditions' },
];

// Build a lookup map for fast prefix matching
export const AUTOCOMPLETE_BY_PREFIX = (prefix) => {
  if (!prefix || prefix.length < 2) return [];
  const lower = prefix.toLowerCase();
  return AUTOCOMPLETE_ITEMS.filter(item => item.label.toLowerCase().startsWith(lower)).slice(0, 12);
};
