// M2TW Script Reference Data — parsed from Docudemons 5.5
// Each entry: { id, description, exports?, params?, sample, class, context? }

export const SCRIPT_EVENTS = [
  { id: 'PreBattle', description: "When a battle is about to start, doesn't work in script", exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest PreBattle', class: 'ET_PRE_BATTLE' },
  { id: 'PostBattle', description: 'When a battle has finished', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest PostBattle', class: 'ET_POST_BATTLE' },
  { id: 'FactionTurnStart', description: 'A Faction has started its turn', exports: 'faction', sample: 'WhenToTest FactionTurnStart', class: 'ET_FACTION_TURN_START' },
  { id: 'PreFactionTurnStart', description: 'A Faction is about to start its turn', exports: 'faction', sample: 'WhenToTest PreFactionTurnStart', class: 'ET_PRE_FACTION_TURN_START' },
  { id: 'FactionTurnEnd', description: 'A Faction has ended its turn', exports: 'faction', sample: 'WhenToTest FactionTurnEnd', class: 'ET_FACTION_TURN_END' },
  { id: 'FactionWarDeclared', description: 'War has been declared by faction on target_faction', exports: 'faction, target_faction, target_religion', sample: 'WhenToTest FactionWarDeclared', class: 'ET_FACTION_WAR_DECLARED' },
  { id: 'FactionAllianceDeclared', description: 'An Alliance has been declared by faction on target_faction', exports: 'faction, target_faction, target_religion', sample: 'WhenToTest FactionAllianceDeclared', class: 'ET_FACTION_ALLIANCE_DECLARED' },
  { id: 'FactionBreakAlliance', description: 'An alliance has been broken by faction on target_faction', exports: 'faction, target_faction, target_religion', sample: 'WhenToTest FactionBreakAlliance', class: 'ET_FACTION_BREAK_ALLIANCE' },
  { id: 'CharacterTurnStart', description: 'A Character has started its turn', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest CharacterTurnStart', class: 'ET_CHARACTER_TURN_START' },
  { id: 'CharacterTurnEnd', description: 'A Character has finished its turn', exports: 'nc_character_record, character_record, faction, region_id, character_type, settlement', sample: 'WhenToTest CharacterTurnEnd', class: 'ET_CHARACTER_TURN_END' },
  { id: 'CharacterTurnEndInSettlement', description: 'A Character has finished its turn in a settlement', exports: 'nc_character_record, character_record, faction, region_id, character_type, settlement', sample: 'WhenToTest CharacterTurnEndInSettlement', class: 'ET_CHARACTER_TURN_END_IN_SETTLEMENT' },
  { id: 'SettlementTurnStart', description: "A Settlement is being processed for the start of its faction's turn", exports: 'faction, settlement, region_id', sample: 'WhenToTest SettlementTurnStart', class: 'ET_SETTLEMENT_TURN_START' },
  { id: 'SettlementTurnEnd', description: "A Settlement is being processed for the end of its faction's turn", exports: 'faction, settlement, region_id', sample: 'WhenToTest SettlementTurnEnd', class: 'ET_SETTLEMENT_TURN_END' },
  { id: 'GeneralCaptureSettlement', description: 'A General has captured a settlement', exports: 'nc_character_record, character_record, faction, region_id, character_type, target_settlement, settlement, target_faction, rsam', sample: 'WhenToTest GeneralCaptureSettlement', class: 'ET_GENERAL_CAPTURE_SETTLEMENT' },
  { id: 'OccupySettlement', description: 'occupy option accepted for settlement occupation', exports: 'nc_character_record, character_record, faction, target_faction, region_id, character_type, target_religion', sample: 'WhenToTest OccupySettlement', class: 'ET_OCCUPY_SETTLEMENT' },
  { id: 'SackSettlement', description: 'sack option accepted for settlement occupation', exports: 'nc_character_record, character_record, faction, target_faction, region_id, character_type, target_religion', sample: 'WhenToTest SackSettlement', class: 'ET_SACK_SETTLEMENT' },
  { id: 'ExterminatePopulation', description: 'exterminate option accepted for settlement occupation', exports: 'nc_character_record, character_record, faction, region_id, character_type, target_faction, target_religion', sample: 'WhenToTest ExterminatePopulation', class: 'ET_EXTERMINATE_POPULATION' },
  { id: 'BuildingCompleted', description: 'A building has been completed', exports: 'faction, settlement, prior_build, advised_build', sample: 'WhenToTest BuildingCompleted', class: 'ET_BUILDING_COMPLETED' },
  { id: 'UnitTrained', description: 'A unit has been trained', exports: 'faction, settlement, resource_description, unit', sample: 'WhenToTest UnitTrained', class: 'ET_UNIT_TRAINED' },
  { id: 'UnitDisbanded', description: 'A unit has been disbanded', exports: 'faction, resource_description, unit', sample: 'WhenToTest UnitDisbanded', class: 'ET_UNIT_DISBANDED' },
  { id: 'AgentCreated', description: 'An agent has been trained', exports: 'character_record, character_type, settlement, faction', sample: 'WhenToTest AgentCreated', class: 'ET_AGENT_CREATED' },
  { id: 'Birth', description: "a child has been born to a family member, exports the child's character record", exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest Birth', class: 'ET_BIRTH' },
  { id: 'CharacterComesOfAge', description: 'A Character has come of age', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest CharacterComesOfAge', class: 'ET_COMING_OF_AGE' },
  { id: 'CharacterMarries', description: 'A Character has married, exports the husband character', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest CharacterMarries', class: 'ET_MARRIAGE' },
  { id: 'BecomesFactionLeader', description: 'The character has been made the faction leader', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest BecomesFactionLeader', class: 'ET_BECOMES_FACTION_LEADER' },
  { id: 'BecomesFactionHeir', description: 'The character has been made the faction heir', exports: 'nc_character_record, character_record, faction, region_id, character_type', sample: 'WhenToTest BecomesFactionHeir', class: 'ET_BECOMES_FACTION_HEIR' },
  { id: 'SpyMission', description: 'A spy mission has completed', exports: 'nc_character_record, character_record, faction, region_id, character_type, target_faction, mission_success_level, target_religion', sample: 'WhenToTest SpyMission', class: 'ET_SPY_MISSION' },
  { id: 'AssassinationMission', description: 'An assassination mission has completed', exports: 'nc_character_record, character_record, faction, region_id, character_type, mission_success_level', sample: 'WhenToTest AssassinationMission', class: 'ET_ASSASSINATION_MISSION' },
  { id: 'DiplomacyMission', description: 'A diplomacy mission has completed', exports: 'nc_character_record, character_record, faction, region_id, character_type, target_faction, mission_success_level, target_religion', sample: 'WhenToTest DiplomacyMission', class: 'ET_DIPLOMACY_MISSION' },
  { id: 'PopeElected', description: 'A new pope has been elected', exports: 'faction, target_faction, target_religion', sample: 'WhenToTest PopeElected', class: 'ET_POPE_ELECTED' },
  { id: 'FactionExcommunicated', description: 'A Faction has been excommunicated', exports: 'faction', sample: 'WhenToTest FactionExcommunicated', class: 'ET_FACTION_EXCOMMUNICATED' },
  { id: 'CrusadeCalled', description: 'A Crusade/Jihad has been called', exports: 'crusade, target_settlement, target_region_id, target_faction, target_religion', sample: 'WhenToTest CrusadeCalled', class: 'ET_CRUSADE_CALLED' },
  { id: 'CrusadeEnds', description: 'A Crusade/Jihad has ended', exports: 'crusade, target_settlement, target_region_id', sample: 'WhenToTest CrusadeEnds', class: 'ET_CRUSADE_ENDS' },
  { id: 'CityRiots', description: 'A settlement has rioted', exports: 'faction, settlement, region_id, target_faction, target_religion', sample: 'WhenToTest CityRiots', class: 'ET_SETTLEMENT_RIOTS' },
  { id: 'CityRebels', description: 'A settlement has rebelled', exports: 'faction, settlement, region_id, target_faction, target_religion', sample: 'WhenToTest CityRebels', class: 'ET_SETTLEMENT_REBELS' },
  { id: 'SettlementUpgraded', description: 'settlement level changed', exports: 'faction, settlement, region_id', sample: 'WhenToTest SettlementUpgraded', class: 'ET_SETTLEMENT_UPGRADED' },
  { id: 'GiveSettlement', description: 'A settlement has been given to another faction', exports: 'faction, settlement, region_id, target_faction, target_religion', sample: 'WhenToTest GiveSettlement', class: 'ET_GIVE_SETTLEMENT' },
  { id: 'EventCounter', description: 'An event counter has changed', exports: 'event_counter', sample: 'WhenToTest EventCounter', class: 'ET_EVENT_COUNTER' },
  { id: 'Disaster', description: 'A disaster has happened', exports: 'event_type', sample: 'WhenToTest Disaster', class: 'ET_DISASTER' },
  { id: 'HordeFormed', description: 'A Faction has formed a horde', exports: 'faction', sample: 'WhenToTest HordeFormed', class: 'ET_FACTION_HORDE_FORMED' },
  { id: 'InterFactionMarriage', description: 'A marriage has occurred between two factions', exports: 'faction, target_faction, target_religion', sample: 'WhenToTest InterFactionMarriage', class: 'ET_INTER_FACTION_MARRIAGE' },
  { id: 'GuildUpgraded', description: 'A guild has been created/upgraded', exports: 'faction, settlement, region_id, resource_description', sample: 'WhenToTest GuildUpgraded', class: 'ET_GUILD_UPGRADED' },
  { id: 'GameReloaded', description: 'A strat map game has been reloaded', exports: 'none', sample: 'WhenToTest GameReloaded', class: 'ET_GAME_RELOADED' },
  { id: 'MissionFinished', description: 'A mission has finished (failed, succeeded or expired)', exports: 'faction, mission_details', sample: 'WhenToTest MissionFinished', class: 'ET_MISSION_FINISHED' },
];

export const SCRIPT_CONDITIONS = [
  // I_ conditions (any context)
  { id: 'I_TurnNumber', params: 'logic_token, turn_number', sample: 'I_TurnNumber > 50', description: 'The current turn number (starts at 0)', context: 'Either', class: 'TURN_NUMBER' },
  { id: 'I_EventCounter', params: 'event_name, logic_token, value', sample: 'I_EventCounter world_is_round > 0', description: 'Check named strat map event counter', context: 'Strat', class: 'I_EVENT_COUNTER' },
  { id: 'I_CompareCounter', params: 'script_counter, logic_token, value', sample: 'I_CompareCounter blib < 17', description: 'Compare a script counter to a value', context: 'Either', class: 'COMPARE_COUNTER' },
  { id: 'I_SettlementExists', params: 'settlement_name', sample: 'I_SettlementExists Segesta', description: 'Does a settlement by this name exist?', context: 'Strat', class: 'SETTLEMENT_EXISTS' },
  { id: 'I_SettlementOwner', params: 'settlement_name, logic_token, faction_type', sample: 'I_SettlementOwner Segesta = romans_julii', description: 'Is this settlement owned by this faction?', context: 'Strat', class: 'SETTLEMENT_OWNER' },
  { id: 'I_NumberOfSettlements', params: 'faction, logic_token, number', sample: 'I_NumberOfSettlements thrace > 3', description: 'How many settlements does the faction hold?', context: 'Strat', class: 'I_NUMBER_OF_SETTLEMENTS' },
  { id: 'I_CharacterExists', params: 'character_name', sample: 'I_CharacterExists Gaius Julius', description: 'Is this character alive and in the campaign?', context: 'Strat', class: 'I_CHARACTER_EXISTS' },
  { id: 'I_CharacterTypeNearTile', params: 'faction, character_type, distance, x, z', sample: 'I_CharacterTypeNearTile romans_julii named_character, 10 48,30', description: 'Is a particular character type of a faction near a particular tile?', context: 'Strat', class: 'I_CHARACTER_NEAR_TILE' },
  { id: 'RandomPercent', params: 'logic_token, percentage', sample: 'RandomPercent > 50', description: 'Pick a number from 0 to 100 at random', context: 'Either', class: 'RANDOM_PERCENT' },
  { id: 'I_LocalFaction', params: 'faction', sample: 'I_LocalFaction romans_julii', description: 'Is the faction the local faction?', context: 'Either', class: 'I_LOCAL_FACTION' },
  { id: 'I_MapName', params: 'map_file_name', sample: 'not I_MapName world\\maps\\campaign\\...', description: 'The qualified file name of the current map relative to the data directory', context: 'Either', class: 'MAP_NAME' },
  { id: 'I_FactionLeaderTrait', params: 'faction_type, trait_description, logic_token, level', sample: 'I_FactionLeaderTrait england BadCommander >= 2', description: 'Test a factions leader traits', context: 'Either', class: 'I_FACTION_LEADER_TRAIT_TEST' },
  { id: 'I_FactionLeaderAttribute', params: 'faction_type, attribute_description, logic_token, level', sample: 'I_FactionLeaderAttribute england Chivalry >= 2', description: 'Test a factions leader attribute', context: 'Either', class: 'I_FACTION_LEADER_ATTRIBUTE_TEST' },
  { id: 'I_NumberUnitsInSettlement', params: 'settlement, unit_type, logic_token, quantity', sample: 'I_NumberUnitsInSettlement Tarquinii roman_city_militia < 5', description: 'How many units are in the settlement?', context: 'Strat', class: 'NUMBER_UNITS_IN_SETTLEMENT' },
  { id: 'I_UnitExists', params: 'Faction, Unit type', sample: 'I_UnitExists England Spear Militia', description: 'Does the faction own any of these units?', context: 'Strat', class: 'I_UNIT_EXISTS' },
  { id: 'I_PlayerHasMission', params: 'missionID', sample: 'I_PlayerHasMission join_crusade', description: 'Test if the player has given mission', context: 'Strat', class: 'I_PLAYER_HAS_MISSION' },
  { id: 'I_CrusadeInProgress', params: 'none', sample: 'I_CrusadeInProgress', description: 'Tests is crusade in progress', context: 'Strat', class: 'I_CRUSADE_IN_PROGRESS' },
  { id: 'I_JihadInProgress', params: 'none', sample: 'I_JihadInProgress', description: 'Tests is jihad in progress', context: 'Strat', class: 'I_JIHAD_IN_PROGRESS' },
  { id: 'I_SettlementUnderSiege', params: 'settlement_name', sample: 'I_SettlementUnderSiege London', description: 'Is the named settlement under siege?', context: 'Strat', class: 'I_SETTLEMENT_UNDER_SIEGE' },
  { id: 'I_InBattle', params: 'none', sample: 'InBattle', description: 'Are we in battle?', context: 'Either', class: 'IN_BATTLE' },
  { id: 'TrueCondition', params: 'none', sample: 'not TrueCondition', description: 'When you need to supply a true/false, for debugging', context: 'Either', class: 'TRUE_CONDITION' },
  // Character conditions
  { id: 'Trait', params: 'trait_description, logic_token, level', sample: 'Trait GoodCommander >= 2', description: 'Test a character trait', context: 'Either', class: 'CHARACTER_TRAIT_TEST', requires: 'character_record' },
  { id: 'Attribute', params: 'attribute_description, logic_token, level', sample: 'Attribute Management >= 2', description: "Test a character's attributes or hidden attributes", context: 'Either', class: 'CHARACTER_ATTRIBUTE_TEST', requires: 'character_record' },
  { id: 'IsGeneral', params: 'none', sample: 'IsGeneral', description: 'Test to see if the character can command a land army', context: 'Either', class: 'CHARACTER_IS_GENERAL', requires: 'character_record' },
  { id: 'IsAdmiral', params: 'none', sample: 'IsAdmiral', description: 'Test to see if the character has an army', context: 'Either', class: 'CHARACTER_IS_ADMIRAL', requires: 'character_record' },
  { id: 'IsFactionLeader', params: 'none', sample: 'IsFactionLeader', description: 'Test to see if the character is a faction leader', context: 'Either', class: 'CHARACTER_IS_LEADER', requires: 'character_record' },
  { id: 'IsFactionHeir', params: 'none', sample: 'IsFactionHeir', description: 'Test to see if the character is a faction heir', context: 'Either', class: 'CHARACTER_IS_HEIR', requires: 'character_record' },
  { id: 'CharFactionType', params: 'faction_type', sample: 'CharFactionType england', description: "Test the character's faction type", context: 'Either', class: 'CHARACTER_FACTION', requires: 'character_record' },
  { id: 'CultureType', params: 'culture_type', sample: 'CultureType greek', description: "Test the character's culture type", context: 'Either', class: 'CHARACTER_CULTURE', requires: 'character_record' },
  { id: 'CharacterReligion', params: 'religion', sample: 'CharacterReligion catholic', description: 'Test the character religion', context: 'Either', class: 'CHARACTER_RELIGION_CHECK', requires: 'character_record' },
  { id: 'AgentType', params: 'character_type', sample: 'AgentType = diplomat', description: 'Test to see if a character is of a particular type', context: 'Strat', class: 'CHARACTER_TYPE_TEST', requires: 'character_record' },
  { id: 'CharacterAge', params: 'logic_token, age', sample: 'CharacterAge >= 75', description: 'Test the age of a character', context: 'Strat', class: 'CHARACTER_AGE', requires: 'character_record' },
  { id: 'EndedInSettlement', params: 'none', sample: 'EndedInSettlement', description: 'test to see if the character is in a settlement', context: 'Either', class: 'CHARACTER_IN_SETTLEMENT', requires: 'character_record' },
  { id: 'IsBesieging', params: 'none', sample: 'IsBesieging', description: 'Is the character besieging a settlement?', context: 'Either', class: 'CHARACTER_IS_BESIEGING', requires: 'character_record' },
  { id: 'IsUnderSiege', params: 'none', sample: 'IsUnderSiege', description: 'Is the character in a garrison residence under siege?', context: 'Either', class: 'CHARACTER_IS_UNDER_SIEGE', requires: 'character_record' },
  { id: 'IsOnCrusade', params: 'none', sample: 'IsOnCrusade', description: 'Test is character on crusade', context: 'Strat', class: 'IS_ON_CRUSADE', requires: 'character_record' },
  { id: 'NoActionThisTurn', params: 'none', sample: 'NoActionThisTurn', description: 'Test to see if the character was idle throughout this turn', context: 'Strat', class: 'CHARACTER_NOT_PERFORMED_ACTION', requires: 'character_record' },
  { id: 'RemainingMPPercentage', params: 'logic_token, level', sample: 'RemainingMPPercentage >= 35.8', description: "Test for percentage of movement points remaining. Check for < 10 for 'hasn't moved'", context: 'Strat', class: 'CHARACTER_MP_REMAINING_PERCENTAGE', requires: 'character_record' },
  { id: 'WonBattle', params: 'none', sample: 'WonBattle', description: 'Did the general win the battle just fought?', context: 'Either', class: 'WON_BATTLE', requires: 'character_record' },
  { id: 'DistanceCapital', params: 'logic_token, level', sample: 'DistanceCapital >= 40', description: 'Does the characters distance to the faction capital exceed the given threshold?', context: 'Strat', class: 'CHARACTER_DISTANCE_CAPITAL', requires: 'character_record' },
  { id: 'FatherTrait', params: 'trait_description, logic_token, level', sample: "FatherTrait VictorRomanVirtue >= 2", description: "Test a character's father's traits for hereditary traits", context: 'Either', class: 'FATHER_TRAIT_TEST', requires: 'character_record' },
  { id: 'FactionLeaderTrait', params: 'trait_description, logic_token, level', sample: 'FactionLeaderTrait VictorRomanVirtue >= 2', description: "Test a character's faction leader traits", context: 'Either', class: 'FACTION_LEADER_TRAIT_TEST', requires: 'character_record' },
  { id: 'SpouseTrait', params: 'trait_description, logic_token, level', sample: 'SpouseTrait VictorRomanVirtue >= 2', description: "Test a character's spouse's traits", context: 'Either', class: 'SPOUSE_TRAIT_TEST', requires: 'character_record' },
  // Faction conditions
  { id: 'FactionType', params: 'faction_type', sample: 'FactionType romans_julii', description: 'Test the faction type', context: 'Either', class: 'FACTION_TYPE_CHECK', requires: 'faction' },
  { id: 'FactionReligion', params: 'faction_religion', sample: 'FactionReligion catholic', description: 'Test the faction religion', context: 'Either', class: 'FACTION_RELIGION_CHECK', requires: 'faction' },
  { id: 'FactionCultureType', params: 'culture_type', sample: 'FactionCultureType greek', description: "Test the faction's culture type", context: 'Either', class: 'FACTION_CULTURE', requires: 'faction' },
  { id: 'Treasury', params: 'logic_token, quantity', sample: 'Treasury > 2000', description: 'Does the cash-in-hand exceed the threshold?', context: 'Strat', class: 'TREASURY', requires: 'faction' },
  { id: 'FactionIncome', params: 'logic_token, level', sample: 'FactionIncome >= 2000', description: 'Test a factions income', context: 'Strat', class: 'FACTION_INCOME', requires: 'faction' },
  { id: 'FactionExcommunicated', params: 'none', sample: 'FactionExcommunicated', description: 'Test if this faction is excommunicated', context: 'Strat', class: 'IS_FACTION_EXCOMMUNICATED', requires: 'faction' },
  { id: 'FactionHasAllies', params: 'none', sample: 'FactionHasAllies', description: 'Test whether the faction is allied with any other faction', context: 'Either', class: 'FACTION_HAS_ALLIES', requires: 'faction' },
  { id: 'DiplomaticStanceFromFaction', params: 'faction_type, logic_token, stance', sample: 'DiplomaticStanceFromFaction romans_julii > Suspicious', description: "Test the faction's diplomatic stance with another specified faction", context: 'Either', class: 'DIPLOMATIC_STANCE_FROM_FACTION', requires: 'faction' },
  { id: 'FactionBuildingExists', params: 'logic_token, test_level', sample: 'FactionBuildingExists >= governors_house', description: 'Test to see if the faction has a building at a particular level', context: 'Strat', class: 'FACTION_BUILDING_LEVEL_EXISTS_TEST', requires: 'faction' },
  { id: 'FactionScore', params: 'score_type, logic_token, faction_type', sample: 'FactionScore military < england', description: 'Test the factions score against that of another faction', context: 'Strat', class: 'FACTION_SCORE_CHECK', requires: 'faction' },
  { id: 'FactionScoreRank', params: 'score_type, logic_token, level', sample: 'FactionScoreRank military < 3', description: "Test the factions score ranking with respect to other discovered, alive factions", context: 'Strat', class: 'FACTION_SCORE_RANK_CHECK', requires: 'faction' },
  { id: 'SettlementsTaken', params: 'logic_token, quantity', sample: 'SettlementsTaken = 6', description: 'How many settlements has the player captured so far during this campaign?', context: 'Either', class: 'SETTLEMENTS_TAKEN', requires: 'faction' },
  { id: 'BattlesFought', params: 'logic_token, quantity', sample: 'BattlesFought = 6', description: 'How many battles has the player fought so far during this campaign?', context: 'Either', class: 'BATTLES_FOUGHT', requires: 'faction' },
  // Settlement conditions
  { id: 'SettlementName', params: 'settlement_name', sample: 'SettlementName Tarquinii', description: 'For scripting - does the settlement have this name', context: 'Either', class: 'SETTLEMENT_NAME', requires: 'settlement' },
  { id: 'SettlementBuildingExists', params: 'building_description, logic_token, test_level', sample: 'SettlementBuildingExists = governors_house', description: 'Test to see if the settlement has a building at a particular level', context: 'Strat', class: 'SETTLEMENT_BUILDING_LEVEL_EXISTS_TEST', requires: 'settlement' },
  { id: 'SettlementLoyaltyLevel', params: 'logic_token, value', sample: 'SettlementLoyaltyLevel > loyalty_rioting', description: 'How loyal is the settlement?', context: 'Either', class: 'SETTLEMENT_LOYALTY_LEVEL', requires: 'settlement' },
  { id: 'SettlementTaxLevel', params: 'logic_token, tax_level', sample: 'SettlementTaxLevel > tax_high', description: 'Is the settlement taxing the populace at a particular level?', context: 'Either', class: 'SETTLEMENT_TAX_LEVEL', requires: 'settlement' },
  { id: 'SettlementType', params: 'city', sample: 'SettlementType city', description: 'Test if the settlement is a city', context: 'Strat', class: 'SETTLEMENT_TYPE', requires: 'settlement' },
  { id: 'SettlementHasPlague', params: 'none', sample: 'SettlementHasPlague', description: 'Is the settlement plague-ridden?', context: 'Strat', class: 'SETTLEMENT_HAS_PLAGUE', requires: 'settlement' },
  { id: 'IsSettlementGarrisoned', params: 'none', sample: 'IsSettlementGarrisoned', description: 'Are there any troops in the settlement?', context: 'Strat', class: 'IS_SETTLEMENT_GARRISONED', requires: 'settlement' },
  { id: 'IsSettlementRioting', params: 'none', sample: 'IsSettlementRioting', description: 'Is the settlement rioting at the moment?', context: 'Strat', class: 'IS_SETTLEMENT_RIOTING', requires: 'settlement' },
  { id: 'HealthPercentage', params: 'logic_token, value', sample: 'HealthPercentage > 35', description: 'Check the health of the settlement', context: 'Strat', class: 'HEALTH_PERCENTAGE', requires: 'settlement' },
  { id: 'RiotRisk', params: 'logic_token, percentage', sample: 'RiotRisk > 30', description: 'What is the chance of this settlement rioting?', context: 'Either', class: 'RIOT_RISK', requires: 'settlement' },
  { id: 'IsCrusadeTarget', params: 'none', sample: 'IsCrusadeTarget', description: 'Test if the settlement is the current crusade target', context: 'Strat', class: 'IS_CRUSADE_TARGET', requires: 'settlement' },
  // Crusade/region/misc
  { id: 'IsCrusade', params: 'none', sample: 'IsCrusade', description: "It's true for crusade and false for jihad", context: 'Strat', class: 'IS_CRUSADE', requires: 'crusade' },
  { id: 'IsJihad', params: 'none', sample: 'IsJihad', description: "It's true for jihad and false for crusade", context: 'Strat', class: 'IS_JIHAD', requires: 'crusade' },
  { id: 'CrusadeOutcome', params: 'outcome (none, success, fail, cancel)', sample: 'CrusadeOutcome success', description: 'Test the crusade/jihad outcome', context: 'Strat', class: 'CRUSADE_OUTCOME', requires: 'crusade' },
  { id: 'Religion', params: 'religion', sample: 'Religion catholic', description: 'Test the religion', context: 'Either', class: 'RELIGION_CHECK' },
  { id: 'TargetReligion', params: 'religion', sample: 'TargetReligion catholic', description: 'Test the target religion', context: 'Either', class: 'TARGET_RELIGION_CHECK', requires: 'target_religion' },
  { id: 'MissionSuccessLevel', params: 'logic_token, success_level', sample: 'MissionSuccessLevel > slightly_successful', description: 'Was the mission sufficiently successful?', context: 'Strat', class: 'MISSION_SUCCESS_TYPE', requires: 'mission_success_level' },
  { id: 'MissionSucceeded', params: 'none', sample: 'MissionSucceeded', description: 'Was the mission sufficiently successful?', context: 'Strat', class: 'MISSION_SUCCEEDED' },
  { id: 'EventCounterType', params: 'event_name', sample: 'EventCounterType world_is_round', description: "Identifies named strat map event by it's name", context: 'Strat', class: 'EVENT_COUNTER_TYPE', requires: 'event_counter' },
  { id: 'EventCounter', params: 'logic_token, value', sample: 'EventCounter > 0', description: 'Check named strat map event counter', context: 'Strat', class: 'EVENT_COUNTER', requires: 'event_counter' },
  { id: 'IsRegionOneOf', params: 'list of regions', sample: 'IsRegionOneOf 0 Caribbean_Isles', description: 'Test is a region in given region list?', context: 'Strat', class: 'IS_REGION_ONE_OF', requires: 'region_id' },
  { id: 'I_IsTriggerTrue', params: 'trigger_name', sample: 'I_IsTriggerTrue sample_trigger_name', description: 'Has this trigger been fired?', context: 'Strat', class: 'TRIGGER_TRUE' },
  { id: 'I_TimerElapsed', params: 'logic_token, timer_id, duration_ms', sample: 'I_TimerElapsed rout_timer > 1000', description: 'How long has it been since the script timer restarted', context: 'Either', class: 'SCRIPT_TIMER_ELAPSED' },
  { id: 'FactionIsLocal', params: 'none', sample: 'FactionIsLocal', description: 'Is the faction the local faction?', context: 'Either', class: 'FACTION_IS_LOCAL', requires: 'faction' },
  { id: 'CharacterIsLocal', params: 'none', sample: 'CharacterIsLocal', description: 'Is the character a member of the local faction?', context: 'Either', class: 'CHARACTER_IS_LOCAL', requires: 'character_record' },
  { id: 'SettlementIsLocal', params: 'none', sample: 'SettlementIsLocal', description: 'Does the settlement belong to the local faction?', context: 'Either', class: 'SETTLEMENT_IS_LOCAL', requires: 'settlement' },
  { id: 'DisasterType', params: 'event_type', sample: 'DisasterType earthquake', description: 'Test to see if a particular disaster just happened', context: 'Strat', class: 'CHARACTER_AFFECTED_BY_DISASTER_EVENT_TEST', requires: 'event_type' },
  { id: 'CampaignDifficulty', params: 'logic_token, difficulty', sample: 'CampaignDifficulty = easy', description: 'Test the factions campaign difficulty level (easy, medium, hard, very_hard)', context: 'Strat', class: 'CAMPAIGN_DIFFICULTY', requires: 'faction' },
  { id: 'I_FirstTimePlay', params: 'faction_type', sample: 'I_FirstTimePlay england', description: 'Has a campaign been played with this faction previously', context: 'Either', class: 'I_FIRST_TIME_PLAYED' },
  { id: 'I_HotseatEnabled', params: 'none', sample: 'I_HotseatEnabled', description: 'Is this currently a hotseat campaign game', context: 'Either', class: 'I_HOTSEAT_ENABLED' },
];

export const SCRIPT_COMMANDS = [
  // Counter & timer
  { id: 'set_counter', params: 'counter_name, value', sample: 'set_counter my_counter 0', description: 'Set a script counter to a value', class: 'SET_COUNTER' },
  { id: 'inc_counter', params: 'counter_name, value', sample: 'inc_counter my_counter 1', description: 'Increment a script counter', class: 'INC_COUNTER' },
  { id: 'dec_counter', params: 'counter_name, value', sample: 'dec_counter my_counter 1', description: 'Decrement a script counter', class: 'DEC_COUNTER' },
  { id: 'start_timer', params: 'timer_id, delay_ms', sample: 'start_timer my_timer 5000', description: 'Start a named script timer', class: 'START_TIMER' },
  // Faction & diplomatic
  { id: 'add_money', params: 'faction_type, amount', sample: 'add_money england 5000', description: 'Add money to faction treasury', class: 'ADD_MONEY' },
  { id: 'set_faction_standing', params: 'faction1, faction2, value', sample: 'set_faction_standing england france 0.5', description: 'Set diplomatic standing between two factions', class: 'SET_FACTION_STANDING' },
  { id: 'alliance', params: 'faction1, faction2', sample: 'alliance england france', description: 'Force an alliance between two factions', class: 'ALLIANCE' },
  { id: 'declare_war', params: 'faction1, faction2', sample: 'declare_war england france', description: 'Force war between two factions', class: 'DECLARE_WAR' },
  { id: 'give_settlement', params: 'settlement_name, faction_type', sample: 'give_settlement London england', description: 'Give a settlement to a faction', class: 'GIVE_SETTLEMENT' },
  { id: 'destroy_faction', params: 'faction_type', sample: 'destroy_faction aztecs', description: 'Immediately destroy a faction', class: 'DESTROY_FACTION' },
  { id: 'excommunicate', params: 'faction_type', sample: 'excommunicate england', description: 'Excommunicate a faction', class: 'EXCOMMUNICATE' },
  { id: 'restore_pope', params: 'none', sample: 'restore_pope', description: 'Restore the papacy', class: 'RESTORE_POPE' },
  { id: 'ai_freeze_faction', params: 'faction_type, true/false', sample: 'ai_freeze_faction aztecs true', description: 'Freeze/unfreeze a faction AI', class: 'AI_FREEZE_FACTION' },
  { id: 'ai_active_set', params: 'on/off', sample: 'ai_active_set off', description: 'Turns AI on or off', class: 'AI_ACTIVE_SET' },
  // Character / unit spawning
  { id: 'spawn_army', params: 'see descr_events.txt format', sample: 'spawn_army faction england ... end_spawn_army', description: 'Spawn an army on the campaign map', class: 'SPAWN_ARMY' },
  { id: 'move_character', params: 'character_name, x, y', sample: 'move_character Rufus 120 80', description: 'Move a named character to tile coordinates', class: 'MOVE_CHARACTER' },
  { id: 'kill_character', params: 'character_name', sample: 'kill_character Rufus', description: 'Kill a named character', class: 'KILL_CHARACTER' },
  { id: 'add_trait', params: 'character_name, trait_name, level', sample: 'add_trait Rufus GoodCommander 3', description: 'Add or set a trait on a named character', class: 'ADD_TRAIT' },
  { id: 'remove_trait', params: 'character_name, trait_name', sample: 'remove_trait Rufus BadCommander', description: 'Remove a trait from a named character', class: 'REMOVE_TRAIT' },
  { id: 'add_ancillary', params: 'character_name, ancillary_name', sample: 'add_ancillary Rufus great_sword', description: 'Add an ancillary to a named character', class: 'ADD_ANCILLARY' },
  { id: 'remove_ancillary', params: 'character_name, ancillary_name', sample: 'remove_ancillary Rufus great_sword', description: 'Remove an ancillary from a named character', class: 'REMOVE_ANCILLARY' },
  // Settlement
  { id: 'add_population', params: 'settlement_name, amount', sample: 'add_population London 500', description: 'Add population to a settlement', class: 'ADD_POPULATION' },
  { id: 'create_building', params: 'settlement_name, building_name', sample: 'create_building London governors_house', description: 'Instantly create a building in a settlement', class: 'CREATE_BUILDING' },
  { id: 'destroy_building', params: 'settlement_name, building_name', sample: 'destroy_building London governors_house', description: 'Instantly destroy a building in a settlement', class: 'DESTROY_BUILDING' },
  { id: 'set_settlement_tax_level', params: 'settlement_name, tax_level', sample: 'set_settlement_tax_level London tax_normal', description: 'Set the tax level of a settlement', class: 'SET_SETTLEMENT_TAX_LEVEL' },
  // Event counter
  { id: 'set_event_counter', params: 'event_name, value', sample: 'set_event_counter world_is_round 1', description: 'Set a named event counter', class: 'SET_EVENT_COUNTER' },
  { id: 'inc_event_counter', params: 'event_name, value', sample: 'inc_event_counter world_is_round 1', description: 'Increment a named event counter', class: 'INC_EVENT_COUNTER' },
  // Messages & advisors
  { id: 'show_message', params: 'message_id', sample: 'show_message my_message', description: 'Show a message to the player', class: 'SHOW_MESSAGE' },
  { id: 'deactivate_advisor', params: 'none', sample: 'deactivate_advisor', description: 'Deactivate advisor messages', class: 'DEACTIVATE_ADVISOR' },
  // Script flow
  { id: 'suspend_unscripted_advice', params: 'true/false', sample: 'suspend_unscripted_advice true', description: 'Suspend or resume unscripted advisor advice', class: 'SUSPEND_UNSCRIPTED_ADVICE' },
  { id: 'steal_esc_key', params: 'true/false', sample: 'steal_esc_key true', description: 'Capture the escape key for scripted events', class: 'STEAL_ESC_KEY' },
  { id: 'terminate_monitor', params: 'none', sample: 'terminate_monitor', description: 'Stop executing the current monitor block', class: 'TERMINATE_MONITOR' },
  { id: 'play_sound', params: 'sound_tag', sample: 'play_sound snd_Fanfare', description: 'Play a named sound event', class: 'PLAY_SOUND' },
  { id: 'stop_sound', params: 'sound_tag', sample: 'stop_sound snd_Fanfare', description: 'Stop a named sound event', class: 'STOP_SOUND' },
  // Battle commands
  { id: 'unit_order_move', params: 'unit_label, x, y, [run]', sample: 'unit_order_move cohort1 100 60 run', description: 'Orders the specified unit to move to the specified position', class: 'UNIT_ORDER_MOVE' },
  { id: 'unit_order_attack_unit', params: 'unit_label, target_unit_label, [run]', sample: 'unit_order_attack_unit cavalry1 enemy4 run', description: 'Orders one unit to attack another', class: 'UNIT_ORDER_ATTACK_UNIT' },
  { id: 'unit_order_halt', params: 'unit_label', sample: 'unit_order_halt cohort1', description: "Orders the specified unit to stop it's orders", class: 'UNIT_ORDER_HALT' },
  { id: 'unit_set_morale', params: 'unit_label, morale_level', sample: 'unit_set_morale carthaginian_peasants wavering', description: "Sets and locks the unit's morale level", class: 'UNIT_SET_MORALE' },
  { id: 'unit_immediate_place', params: 'unit_label, location, angle_in_degrees, [width]', sample: 'unit_immediate_place archers1 big_hill 0 20', description: 'Immediately positions the unit at the given location', class: 'UNIT_IMMEDIATE_PLACE' },
  { id: 'kill_unit', params: 'unit_label', sample: 'kill_unit carthaginians2', description: 'Completely wipes out the specified unit', class: 'KILL_UNIT' },
  { id: 'reduce_unit_strength', params: 'unit_label, percentage', sample: 'reduce_unit_strength carthaginians2 50', description: "Kills enough men to reduce a unit to the specified percentage of it's original strength", class: 'REDUCE_UNIT_STRENGTH' },
  { id: 'unit_set_experience', params: 'unit_label, new_experience_level', sample: 'unit_set_experience roman_general 7', description: "Sets the specified unit's experience level (0-9)", class: 'UNIT_SET_EXPERIENCE' },
  { id: 'unit_order_change_formation', params: 'unit_label, formation_type', sample: 'unit_order_change_formation legionary_cohort testudo', description: "Changes the specified unit's formation", class: 'UNIT_ORDER_CHANGE_FORMATION' },
  { id: 'pause_battle', params: 'none', sample: 'pause_battle', description: 'Pauses the battle', class: 'PAUSE_BATTLE' },
  { id: 'battle_set_speed', params: 'speed (0.0 -> 10.0)', sample: 'battle_set_speed 1.0', description: 'Sets battle speed', class: 'BATTLE_SET_SPEED' },
];

export const CONSOLE_COMMANDS = [
  { id: 'add_money', params: '<opt:faction_type>, <amount>', sample: 'add_money england, 5000', description: 'Adds money to faction treasury. Max 40000.', usedIn: 'strat' },
  { id: 'add_population', params: '<settlement_name> <amount>', sample: 'add_population London 2000', description: 'Adds population to a settlement, can be negative.', usedIn: 'strat' },
  { id: 'create_building', params: '<settlement_name> <building_level>', sample: 'create_building London governors_house', description: 'Creates a building in the specified settlement.', usedIn: 'strat' },
  { id: 'move_character', params: '<character_name> <x> <y>', sample: 'move_character Rufus 120 80', description: 'Moves a character to the specified tile coordinates.', usedIn: 'strat' },
  { id: 'kill_character', params: '<character_name>', sample: 'kill_character Rufus', description: 'Kills the named character.', usedIn: 'strat' },
  { id: 'add_trait', params: '<character_name> <trait> <level>', sample: 'add_trait Rufus GoodCommander 3', description: 'Adds a trait to a character.', usedIn: 'strat' },
  { id: 'add_ancillary', params: '<character_name> <ancillary>', sample: 'add_ancillary Rufus great_sword', description: 'Adds an ancillary item to a character.', usedIn: 'strat' },
  { id: 'capture_settlement', params: '<settlement_name>', sample: 'capture_settlement London', description: 'Gives a settlement to the currently selected character\'s faction.', usedIn: 'strat' },
  { id: 'give_settlement', params: '<settlement_name> <faction>', sample: 'give_settlement London france', description: 'Gives a settlement to the specified faction.', usedIn: 'strat' },
  { id: 'destroy_building', params: '<settlement_name> <building_level>', sample: 'destroy_building London governors_house', description: 'Destroys a building in the specified settlement.', usedIn: 'strat' },
  { id: 'auto_win', params: '<attacker/defender>', sample: 'auto_win attacker', description: 'Auto-resolve the current battle for the specified side.', usedIn: 'battle' },
  { id: 'toggle_fow', params: 'none', sample: 'toggle_fow', description: 'Toggles the fog of war on the campaign map.', usedIn: 'strat' },
  { id: 'show_cursorstat', params: 'none', sample: 'show_cursorstat', description: 'Shows cursor position and region information.', usedIn: 'strat' },
  { id: 'date', params: '<season> <year>', sample: 'date summer 1200', description: 'Sets the campaign date.', usedIn: 'strat' },
  { id: 'diplomatic_stance', params: '<faction1> <faction2> <stance>', sample: 'diplomatic_stance england france allied', description: 'Sets the diplomatic stance between two factions.', usedIn: 'strat' },
  { id: 'process_cq', params: '<settlement_name>', sample: 'process_cq London', description: 'Process construction queue instantly for settlement.', usedIn: 'strat' },
  { id: 'process_rq', params: '<settlement_name>', sample: 'process_rq London', description: 'Process recruitment queue instantly for settlement.', usedIn: 'strat' },
  { id: 'ai_turn_speed', params: '<multiplier>', sample: 'ai_turn_speed 10', description: 'Sets the maximum speed of turn processing during AI round.', usedIn: 'strat' },
  { id: 'invulnerable_general', params: '<character_name>', sample: 'invulnerable_general Rufus', description: 'Makes a general invulnerable.', usedIn: 'strat' },
  { id: 'list_characters', params: '<faction>', sample: 'list_characters england', description: "Lists all faction characters' position and details.", usedIn: 'strat' },
  { id: 'list_settlements', params: '<faction>', sample: 'list_settlements england', description: 'Lists all faction settlements.', usedIn: 'strat' },
  { id: 'output_unit_positions', params: 'none', sample: 'output_unit_positions', description: 'Output unit positions to file (battle only).', usedIn: 'battle' },
  { id: 'regenerate_radar', params: 'none', sample: 'regenerate_radar', description: 'Regenerates the radar map.', usedIn: 'strat' },
  { id: 'season', params: '<summer/winter>', sample: 'season summer', description: 'Changes the current season.', usedIn: 'strat' },
  { id: 'show_terrain_lines', params: 'none', sample: 'show_terrain_lines', description: 'Displays terrain lines on the battle map.', usedIn: 'battle' },
  { id: 'speedy_battle', params: 'none', sample: 'speedy_battle', description: 'Toggle speedy battle resolution.', usedIn: 'battle' },
];
